language: go
go:
 - 1.10.3
notifications:
  email: false
before_install:
  - curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip && unzip protoc-3.2.0-linux-x86_64.zip -d protoc3 && chmod +x protoc3/bin/* && sudo mv protoc3/bin/* /usr/local/bin && sudo mv protoc3/include/* /usr/local/include/
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - make install_bins_linux
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get -u github.com/lyft/protoc-gen-validate
  - go get github.com/jteeuwen/go-bindata/...
install:
  - hack/check-changelog.sh
  - make
  - make test
sudo: false
